nohup python3 -u demo.py --data_name wine --missing_mechanism MAR >> ./logs/wine.txt 2>&1 ;
nohup python3 -u demo.py --data_name heart --missing_mechanism MAR >> ./logs/heart.txt 2>&1 ;
nohup python3 -u demo.py --data_name breast --missing_mechanism MAR >> ./logs/breast.txt 2>&1 ;
nohup python3 -u demo.py --data_name car --missing_mechanism MAR >> ./logs/car.txt 2>&1 ;
nohup python3 -u demo.py --data_name wireless --missing_mechanism MAR >> ./logs/wireless.txt 2>&1 ;
nohup python3 -u demo.py --data_name abalone --missing_mechanism MAR >> ./logs/abalone.txt 2>&1 ;
nohup python3 -u demo.py --data_name turkiye --missing_mechanism MAR >> ./logs/turkiye.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MAR >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MAR >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MAR >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name wine --missing_mechanism MNARL >> ./logs/wine.txt 2>&1 ;
nohup python3 -u demo.py --data_name heart --missing_mechanism MNARL >> ./logs/heart.txt 2>&1 ;
nohup python3 -u demo.py --data_name breast --missing_mechanism MNARL >> ./logs/breast.txt 2>&1 ;
nohup python3 -u demo.py --data_name car --missing_mechanism MNARL >> ./logs/car.txt 2>&1 ;
nohup python3 -u demo.py --data_name wireless --missing_mechanism MNARL >> ./logs/wireless.txt 2>&1 ;
nohup python3 -u demo.py --data_name abalone --missing_mechanism MNARL >> ./logs/abalone.txt 2>&1 ;
nohup python3 -u demo.py --data_name turkiye --missing_mechanism MNARL >> ./logs/turkiye.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MNARL >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MNARL >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MNARL >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --missing_rate 0.1 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --missing_rate 0.1 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --missing_rate 0.1 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --missing_rate 0.2 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --missing_rate 0.2 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --missing_rate 0.2 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --missing_rate 0.3 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --missing_rate 0.3 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --missing_rate 0.3 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --missing_rate 0.4 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --missing_rate 0.4 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --missing_rate 0.4 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --missing_rate 0.5 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --missing_rate 0.5 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --missing_rate 0.5 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --missing_rate 0.6 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --missing_rate 0.6 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --missing_rate 0.6 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --missing_rate 0.7 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --missing_rate 0.7 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --missing_rate 0.7 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --missing_rate 0.8 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --missing_rate 0.8 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --missing_rate 0.8 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --feature_dim 0.1 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --feature_dim 0.1 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --feature_dim 0.1 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --feature_dim 0.2 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --feature_dim 0.2 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --feature_dim 0.2 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --feature_dim 0.3 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --feature_dim 0.3 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --feature_dim 0.3 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --feature_dim 0.4 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --feature_dim 0.4 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --feature_dim 0.4 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --feature_dim 0.5 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --feature_dim 0.5 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --feature_dim 0.5 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --feature_dim 0.6 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --feature_dim 0.6 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --feature_dim 0.6 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --feature_dim 0.7 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --feature_dim 0.7 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --feature_dim 0.7 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --feature_dim 0.8 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --feature_dim 0.8 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --feature_dim 0.8 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --feature_dim 0.9 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --feature_dim 0.9 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --feature_dim 0.9 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --training_size 0.1 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --training_size 0.1 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --training_size 0.1 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --training_size 0.2 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --training_size 0.2 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --training_size 0.2 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --training_size 0.3 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --training_size 0.3 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --training_size 0.3 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --training_size 0.4 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --training_size 0.4 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --training_size 0.4 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --training_size 0.5 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --training_size 0.5 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --training_size 0.5 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --training_size 0.6 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --training_size 0.6 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --training_size 0.6 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --training_size 0.7 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --training_size 0.7 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --training_size 0.7 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --training_size 0.8 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --training_size 0.8 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --training_size 0.8 >> ./logs/shuttle.txt 2>&1 ;
nohup python3 -u demo.py --data_name letter --missing_mechanism MCAR --training_size 0.9 >> ./logs/letter.txt 2>&1 ;
nohup python3 -u demo.py --data_name chess --missing_mechanism MCAR --training_size 0.9 >> ./logs/chess.txt 2>&1 ;
nohup python3 -u demo.py --data_name shuttle --missing_mechanism MCAR --training_size 0.9 >> ./logs/shuttle.txt 2>&1 ;