nohup python3 -u main_edit_miao.py --data_name wine --edit_idx 0 >> ./logs/miao_revision_wine.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name heart --edit_idx 0 >> ./logs/miao_revision_heart.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name breast --edit_idx 0 >> ./logs/miao_revision_breast.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name car --edit_idx 0 >> ./logs/miao_revision_car.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name wireless --edit_idx 0 >> ./logs/miao_revision_wireless.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name abalone --edit_idx 0 >> ./logs/miao_revision_abalone.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name turkiye --edit_idx 0 >> ./logs/miao_revision_turkiye.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name letter --edit_idx 0 >> ./logs/miao_revision_letter.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name chess --edit_idx 0 >> ./logs/miao_revision_chess.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name shuttle --edit_idx 1 >> ./logs/miao_revision_shuttle.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name wine --edit_idx 1 >> ./logs/miao_revision_wine.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name heart --edit_idx 1 >> ./logs/miao_revision_heart.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name breast --edit_idx 1 >> ./logs/miao_revision_breast.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name car --edit_idx 1 >> ./logs/miao_revision_car.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name wireless --edit_idx 1 >> ./logs/miao_revision_wireless.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name abalone --edit_idx 1 >> ./logs/miao_revision_abalone.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name turkiye --edit_idx 1 >> ./logs/miao_revision_turkiye.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name letter --edit_idx 1 >> ./logs/miao_revision_letter.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name chess --edit_idx 1 >> ./logs/miao_revision_chess.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name shuttle --edit_idx 1 >> ./logs/miao_revision_shuttle.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name wine --edit_idx 2 >> ./logs/miao_revision_wine.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name heart --edit_idx 2 >> ./logs/miao_revision_heart.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name breast --edit_idx 2 >> ./logs/miao_revision_breast.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name car --edit_idx 2 >> ./logs/miao_revision_car.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name wireless --edit_idx 2 >> ./logs/miao_revision_wireless.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name abalone --edit_idx 2 >> ./logs/miao_revision_abalone.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name turkiye --edit_idx 2 >> ./logs/miao_revision_turkiye.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name letter --edit_idx 2 >> ./logs/miao_revision_letter.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name chess --edit_idx 2 >> ./logs/miao_revision_chess.txt 2>&1 &&
nohup python3 -u main_edit_miao.py --data_name shuttle --edit_idx 2 >> ./logs/miao_revision_shuttle.txt 2>&1 &