#!/bin/bash

nohup python3 -u main_hnsw_batch.py --data_name wine --batch_size 16 >> ./logs/batchsize_wine.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name heart --batch_size 16 >> ./logs/batchsize_heart.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name breast --batch_size 16 >> ./logs/batchsize_breast.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name car --batch_size 16 >> ./logs/batchsize_car.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wireless --batch_size 16 >> ./logs/batchsize_wireless.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name abalone --batch_size 16 >> ./logs/batchsize_abalone.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name turkiye --batch_size 16 >> ./logs/batchsize_turkiye.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name letter --batch_size 16 >> ./logs/batchsize_letter.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name chess --batch_size 16 >> ./logs/batchsize_chess.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name shuttle --batch_size 16 >> ./logs/batchsize_shuttle.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wine --batch_size 32 >> ./logs/batchsize_wine.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name heart --batch_size 32 >> ./logs/batchsize_heart.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name breast --batch_size 32 >> ./logs/batchsize_breast.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name car --batch_size 32 >> ./logs/batchsize_car.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wireless --batch_size 32 >> ./logs/batchsize_wireless.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name abalone --batch_size 32 >> ./logs/batchsize_abalone.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name turkiye --batch_size 32 >> ./logs/batchsize_turkiye.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name letter --batch_size 32 >> ./logs/batchsize_letter.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name chess --batch_size 32 >> ./logs/batchsize_chess.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name shuttle --batch_size 32 >> ./logs/batchsize_shuttle.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wine --batch_size 64 >> ./logs/batchsize_wine.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name heart --batch_size 64 >> ./logs/batchsize_heart.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name breast --batch_size 64 >> ./logs/batchsize_breast.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name car --batch_size 64 >> ./logs/batchsize_car.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wireless --batch_size 64 >> ./logs/batchsize_wireless.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name abalone --batch_size 64 >> ./logs/batchsize_abalone.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name turkiye --batch_size 64 >> ./logs/batchsize_turkiye.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name letter --batch_size 64 >> ./logs/batchsize_letter.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name chess --batch_size 64 >> ./logs/batchsize_chess.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name shuttle --batch_size 64 >> ./logs/batchsize_shuttle.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wine --batch_size 128 >> ./logs/batchsize_wine.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name heart --batch_size 128 >> ./logs/batchsize_heart.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name breast --batch_size 128 >> ./logs/batchsize_breast.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name car --batch_size 128 >> ./logs/batchsize_car.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wireless --batch_size 128 >> ./logs/batchsize_wireless.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name abalone --batch_size 128 >> ./logs/batchsize_abalone.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name turkiye --batch_size 128 >> ./logs/batchsize_turkiye.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name letter --batch_size 128 >> ./logs/batchsize_letter.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name chess --batch_size 128 >> ./logs/batchsize_chess.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name shuttle --batch_size 128 >> ./logs/batchsize_shuttle.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wine --batch_size 256 >> ./logs/batchsize_wine.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name heart --batch_size 256 >> ./logs/batchsize_heart.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name breast --batch_size 256 >> ./logs/batchsize_breast.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name car --batch_size 256 >> ./logs/batchsize_car.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wireless --batch_size 256 >> ./logs/batchsize_wireless.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name abalone --batch_size 256 >> ./logs/batchsize_abalone.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name turkiye --batch_size 256 >> ./logs/batchsize_turkiye.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name letter --batch_size 256 >> ./logs/batchsize_letter.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name chess --batch_size 256 >> ./logs/batchsize_chess.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name shuttle --batch_size 256 >> ./logs/batchsize_shuttle.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wine --batch_size 512 >> ./logs/batchsize_wine.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name heart --batch_size 512 >> ./logs/batchsize_heart.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name breast --batch_size 512 >> ./logs/batchsize_breast.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name car --batch_size 512 >> ./logs/batchsize_car.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name wireless --batch_size 512 >> ./logs/batchsize_wireless.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name abalone --batch_size 512 >> ./logs/batchsize_abalone.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name turkiye --batch_size 512 >> ./logs/batchsize_turkiye.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name letter --batch_size 512 >> ./logs/batchsize_letter.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name chess --batch_size 512 >> ./logs/batchsize_chess.txt 2>&1 &&
nohup python3 -u main_hnsw_batch.py --data_name shuttle --batch_size 512 >> ./logs/batchsize_shuttle.txt 2>&1 &
